[package]
name = "langlog"
version = "1.0.0"
edition = "2024"

[dependencies]
terminal = {path = "./terminal"}
log = "0.4.29"
pretty_env_logger = "0.5.0"
thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
csv = "1.4.0"
